### ISSUE TITLE
サーバを運ぶ

### ISSUE THREAD

**Issue by kvvzr** [kwzrhouse/api.kwzrhouse.net#3]
車が必要なんです @mactkg

**Comment by mactkg** [comment]
いつやる？今日でもいいけど

2015年4月15日水曜日、Kazumasa Kawazurenotifications@github.comさんは書きました:

**Comment by kvvzr** [comment]
5限終わったあととかどうですか

**Comment by mactkg** [comment]
あいてます

2015年4月15日水曜日、Kazumasa Kawazurenotifications@github.comさんは書きました:

**Comment by kvvzr** [comment]
運びました〜〜〜〜〜〜〜
